blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/quikapp-dev/docs
    about: Check our documentation for guides and API references
  - name: Discussions
    url: https://github.com/quikapp-dev/quikapp/discussions
    about: Ask questions and share ideas with the community
